### ISSUE TITLE
Logfiles can't be loaded because of missing metadata type

### ISSUE THREAD

**Issue by saarnold** [rock-core/tools-orocosrb#125]
After the recent changes in c0d613a05ea347d027d5fbb8fb087e89d2c33702 it is mandatory that every stream provides the `rock_stream_type`. It appears not all logs have this flag. Can we add backward compatibility for them?

Is it somewhere defined which metadata must be present for each log stream?

This is the error message:
```
pocolog.rb[INFO]: done
orocos.rb[ERROR]: Cannot load logfiles
/home/sirius/silana/tools/orocos.rb/lib/orocos/log/task_context.rb:768:in `add_stream': stream 'pose_provider.pose_samples' has no rock_stream_type metadata, cannot guess whether it should back a port or a property (ArgumentError)
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:938:in `load_task_from_stream'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:955:in `block in load_log_file'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:950:in `each'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:950:in `load_log_file'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:1024:in `block in load'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:987:in `each'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:987:in `load'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:176:in `open'
	from /home/sirius/silana/gui/vizkit/bin/rock-replay:89:in `<main>'
```

**Comment by doudou** [comment]
Just for my information, how old are these logs ?

**Comment by doudou** [comment]
And from a documentation perspective, this is actually one of the very few things that had been standardized very early: http://rock.opendfki.de/trac/wiki/WikiStart/Standards/RG8

**Comment by saarnold** [comment]
The logs are actually not old, but apparently are violating this standard :roll_eyes:
I'll fix this for the future. For the meantime would backward compatibility be feasible?
Otherwise converting the logs would be the only fix I guess.

**Comment by doudou** [comment]
> I'll fix this for the future. For the meantime would backward compatibility be feasible?

How were these logs generated ? `rock_stream_type` was supposed to be generated by orocos.rb for ages.

**Comment by doudou** [comment]
Anyways, please test https://github.com/rock-core/tools-orocosrb/pull/126

**Comment by saarnold** [comment]
> How were these logs generated ? rock_stream_type was supposed to be generated by orocos.rb for ages.

They have been created using the orocos cpp API.

> Anyways, please test #126

This fixes the issue. Thanks!
