### ISSUE TITLE
No superclass method `read_helper' for OutputPort

### ISSUE THREAD

**Issue by vbargsten** [rock-core/tools-orocosrb#131]
Had some old code failing with error message:

```

pry(main)> filter_reader.read_helper(sample, true)
NoMethodError: super: no superclass method `read_helper' for #<Orocos::OutputReader:0x000056073a5dab00>
Did you mean?  read_new
from /home/vbargsten/rock_compi/tools/orocos.rb/lib/orocos/output_reader.rb:21:in `read_helper'

```

https://github.com/rock-core/tools-orocosrb/blob/453184c1b555d6143a5a9d9f1ae88527068a07f9/lib/orocos/output_reader.rb#L21

**Comment by doudou** [comment]
This method still exists, but isn't used anywhere actually. So, old code indeed.

**Comment by vbargsten** [comment]
Are you sure? I can only find read_helper in OutputReader, but nowhere else. Calling super then fails, i.e.this method is broken and should be fixed or removed.

**Comment by doudou** [comment]
My answer was ambiguous ... Yes, I agree with you.

It has been removed by c7f516d451dc99c951f6d631913dedb32b527982. Was never part of the public API (we're tagging those with `@api private` now)
