### ISSUE TITLE
Unexpected behaviour for Types:: System

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/tools-orocosrb#19]
Hey,
If I execute this script : 

#! /usr/bin/env ruby
require 'orocos'
require 'base/typelib/rigid_body_state'
include Orocos

Orocos.initialize
rbs = Types::Base::Samples::RigidBodyState.new 

It fails, as Types::Base::Samples .. is an uninitialized Constant.

If I add a
stub = Orocos.name_service.get("command_server")
before the rbs = everything is fine. It seems that this line 
does some magic. 
I would expect the behavior, that Types::Base::Samples::RigidBodyState is
available after the require of require 'base/typelib/rigid_body_state'.

**Comment by doudou** [comment]
The API actually already existed, it's call Orocos.load_typekit_for, and since I've already seen it used in the wild a few times I guess most people know it exists.

If one wants to create a PR to alias e.g. require_type to it, be my guest. In the meantime I'm closing this.
