### ISSUE TITLE
Bad error message if operation throws an exception

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/tools-orocosrb#25]
If a called operation throws an (C++) Exception, this 
results in the error message:
"unspecified error in the CORBA layer"
We should try to enhance this error message, to say 
that the operation threw an exception.

**Comment by doudou** [comment]
This is not an orocos.rb issue. Create a relevant ticket on RTT for it. One example of StdException usage can be found in ConfigurationInterfaceI.cpp
