### ISSUE TITLE
 `step': undefined method `sample_info' for #<Pocolog::StreamAligner:0x00000005e79e60> (NoMethodError)

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/tools-orocosrb#38]
Seems related to #34 

Now rock-replay results in the following error:

/home/goldhoorn/bootstraps/test/tools/orocos.rb/lib/orocos/log/replay.rb:605:in `step': undefined method `sample_info' for #<Pocolog::StreamAligner:0x00000005e79e60> (NoMethodError)
	from /home/goldhoorn/bootstraps/test/tools/orocos.rb/lib/orocos/log/replay.rb:436:in `align'
	from /home/goldhoorn/bootstraps/test/gui/vizkit/lib/vizkit/widgets/log_control/log_control.rb:86:in `config'
	from /home/goldhoorn/bootstraps/test/gui/vizkit/lib/vizkit/vizkit.rb:54:in `setup_widget'
	from /home/goldhoorn/bootstraps/test/gui/vizkit/lib/vizkit/vizkit.rb:93:in `widget_from_options'
	from /home/goldhoorn/bootstraps/test/gui/vizkit/lib/vizkit/vizkit.rb:98:in `control'
	from replay.rb:57:in `block in <main>'
	from /home/goldhoorn/bootstraps/test/tools/orocos.rb/lib/orocos/process.rb:675:in `block in run'
	from /home/goldhoorn/bootstraps/test/tools/orocos.rb/lib/orocos/process.rb:1063:in `guard'
	from /home/goldhoorn/bootstraps/test/tools/orocos.rb/lib/orocos/process.rb:674:in `run'
	from /home/goldhoorn/bootstraps/test/tools/orocos.rb/lib/orocos/process.rb:107:in `run'
	from replay.rb:23:in `<main>'

**Comment by doudou** [comment]
Sorry ... This PR should definitely not have been merged as it depended on code in pocolog that was not merged. I merged the other PR now (as I have been using it for the last weeks), it should work again.
