### ISSUE TITLE
release candidate: Async no longer works in case of missing typekits

### ISSUE THREAD

**Issue by D-Alex** [rock-core/tools-orocosrb#56]
Async no longer works witth tasks which have a missing typekit. The reason is that some methods raise an argument error which are not catched by async's event loop (see backtrace). Ideally the methods would raise something more meaningfull which can be safely catched by async. I do not really like to catch ArgumentsErrors because they usually mean there is a programming error.

Any ideas?

    /home/aduda/dev/rock_master/tools/orogen/lib/orogen/loaders/base.rb:338:in `imported_typekits_for': /_gps_Solution is not defined by any typekits loaded so far (ArgumentError)
	from /home/aduda/dev/rock_master/tools/orogen/lib/orogen/loaders/base.rb:400:in `m_type?'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/default_loader.rb:65:in `block in export_registry_to_ruby'
	from /home/aduda/dev/rock_master/install/lib/ruby/2.1.0/typelib/registry.rb:245:in `block in export_to_ruby'
	from /home/aduda/dev/rock_master/install/lib/ruby/2.1.0/typelib/registry.rb:94:in `each_type'
	from /home/aduda/dev/rock_master/install/lib/ruby/2.1.0/typelib/registry.rb:94:in `each'
	from /home/aduda/dev/rock_master/install/lib/ruby/2.1.0/typelib/registry.rb:228:in `export_to_ruby'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/default_loader.rb:60:in `export_registry_to_ruby'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/default_loader.rb:51:in `register_typekit_model'
	from /home/aduda/dev/rock_master/tools/orogen/lib/orogen/loaders/base.rb:258:in `register_typekit_model'
	from /home/aduda/dev/rock_master/tools/orogen/lib/orogen/loaders/base.rb:243:in `typekit_model_from_name'
	from /home/aduda/dev/rock_master/tools/orogen/lib/orogen/loaders/pkg_config.rb:241:in `typekit_for'
	from /home/aduda/dev/rock_master/tools/orogen/lib/orogen/loaders/aggregate.rb:120:in `block in typekit_for'
	from /home/aduda/dev/rock_master/tools/orogen/lib/orogen/loaders/aggregate.rb:117:in `each'
	from /home/aduda/dev/rock_master/tools/orogen/lib/orogen/loaders/aggregate.rb:117:in `typekit_for'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/typekits.rb:183:in `load_typekit_for'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/typekits.rb:260:in `find_type_by_orocos_type_name'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/task_context_base.rb:49:in `ensure_type_available'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/task_context_base.rb:25:in `initialize'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/task_context.rb:16:in `initialize'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/task_context.rb:491:in `new'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/task_context.rb:491:in `property'
	from /home/aduda/dev/rock_master/tools/utilrb/lib/utilrb/thread_pool.rb:440:in `call'
	from /home/aduda/dev/rock_master/tools/utilrb/lib/utilrb/thread_pool.rb:440:in `sync'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/task_context_base.rb:289:in `call_with_async'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/task_context_base.rb:299:in `property'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:895:in `block (2 levels) in connect_property'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/object_base.rb:197:in `instance_eval'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/object_base.rb:197:in `emitting'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/object_base.rb:203:in `disable_emitting'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:893:in `block in connect_property'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:891:in `synchronize'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:891:in `connect_property'
	from /home/aduda/dev/rock_master/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:587:in `block in property'
	from /home/aduda/dev/rock_master/tools/utilrb/lib/utilrb/thread_pool.rb:191:in `call'
	from /home/aduda/dev/rock_master/tools/utilrb/lib/utilrb/thread_pool.rb:191:in `execute'
	from /home/aduda/dev/rock_master/tools/utilrb/lib/utilrb/thread_pool.rb:584:in `block in spawn_thread'
	from /home/aduda/dev/rock_master/tools/utilrb/lib/utilrb/event_loop.rb:622:in `step'
	from /home/aduda/dev/rock_master/gui/vizkit/lib/vizkit/vizkit.rb:133:in `block in exec'
	from /usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:2427:in `call'
	from /usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:2427:in `invoke'
	from /usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `qt_metacall'
	from /usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `method_missing'
	from /usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `exec'
	from /home/aduda/dev/rock_master/gui/vizkit/lib/vizkit/vizkit.rb:137:in `exec'
	from /home/aduda/dev/rock_master/gui/vizkit/bin/rock-display:107:in `<main>'

**Comment by doudou** [comment]
One: you're right, the exception should be made specific. I'm testing a commit in that direction

Second: the bug you have should not be ignored, because it looks very weird. A type gets loaded, somehow, but then the loaders cannot find the typekit which loaded it. If you give me a hint on how to reproduce, that would be helpful ...

**Comment by doudou** [comment]
If you could test https://github.com/orocos-toolchain/orogen/pull/48 on the RC, I would be grateful

**Comment by D-Alex** [comment]
I will try to reproduce it tomorrow on my machine. The case was a plain rock rc installation on one side and a bit outdated (3 months old) installation with an orogen imu_xsens task on the other side.

**Comment by D-Alex** [comment]
Currently, I cannot reproduce it. I do not even know which task was involved needing gps_Solution. I thought it was the imu but it's not. Next time I will get access to the system (crawler from external partner) I will debug it. I thought the problem is just because of missing typekits but your are right it looks weird.

**Comment by 2maz** [comment]
Also encountered the problem, when trying to use rock-display to connect to a remote host: 
```ruby
/opt/workspace/rock-rc/tools/orogen/lib/orogen/loaders/base.rb:338:in `imported_typekits_for': /_metadata_TaskContext is not defined by any typekits loaded so far (ArgumentError)
	from /opt/workspace/rock-rc/tools/orogen/lib/orogen/loaders/base.rb:400:in `m_type?'
ArgumentError:  /_metadata_TaskContext is not defined by any typekits loaded so far
```

Looks like the error should be triggered when typekits on two systems are
1. inconsistent, e.g. like here when build with / without metadata support!?
2. a typekit in use exists only on the remote host, but not where rock-display is running

**Comment by goldhoorn** [comment]
I do not have problems with unloaded types. I can access a meessage_producer with metadata from a task inspector withour metadata, in only get a error mesage in the task-inspector that:

```Orocos::Async::CORBA::roperty metadata is not reachable```

But everything else works as expected.

When i starting a complete unknown task i get on the command line a warning:

```orocos.rb[WARN]: /sysmon is a task context of class sysmon::Task, but I cannot find the description for it, falling back
```

And a few wiered backtraces within the TaskInspector Value section, Foo is not defined by and typekit..." but this is for me okay.


For me this seems a non-blocker to do the release, thoughts?

**Comment by D-Alex** [comment]
Like Thomas said. The problem seems to be triggered by typekits which are for example strict subsets of the one running on the robot. In these cases, orocos correctly loads the typekits but aborts with an ArgumentError because the typekit is missing some types.

I would at least catch the error in the async layer until we nailed it down.

**Comment by goldhoorn** [comment]
Hmh,
when i do have a message_producer WITH metadata this is a superset of 
the installation with rock-display.

I really would like to 'release' tomorrow...
...so today last chance for patches...

Best,
Matthias

On 18.05.2015 10:39, Alexander Duda wrote:
>
> Like Thomas said. The problem seems to be triggered by typekits which 
> are for example strict subsets of the one running on the robot. In 
> these cases, orocos correctly loads the typekits but aborts with an 
> ArgumentError because the typekit is missing some types.
>
> I would at least catch the error in the async layer until we nailed it 
> down.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/issues/56#issuecomment-102976252>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by 2maz** [comment]
Applying: 
- orocos-toolchain/orogen#48
- rock-core/tools-orocosrb#57
fixes the issue now for my test case.

**Comment by goldhoorn** [comment]
I apply the pached, reopen if bug is not solved
