### ISSUE TITLE
Ruby types don't seem to be exported anymore

### ISSUE THREAD

**Issue by 2maz** [rock-core/tools-orocosrb#67]
Changed export algorithm on typelib or a missing integration in orocos.rb leads to a failing export of base types to ruby:

```ruby
irb -rorocos
irb(main):001:0> Orocos.load_typekit 'base'
=> ["base"]
irb(main):002:0> Types::Base::Samples::RigidBodyState.new
NameError: uninitialized constant Types::Base::Samples
	from (irb):2
	from /usr/bin/irb2.0:12:in `<main>'

**Comment by doudou** [comment]
While this is not a fix (and a fix is required), for the time being you can use the new syntax

~~~
Types.base.samples.RigidBodyState
~~~

**Comment by doudou** [comment]
Should be fixed by applying both https://github.com/rock-core/tools-orocosrb/pull/68 and https://github.com/rock-core/base-types/pull/53.

I don't know why it worked for me (new-style exports) even though it should not have... And no time to investigate.

**Comment by 2maz** [comment]
Now I get:

``` ruby
irb(main):003:0> Types::Base::Samples::RidigBodyState.new
Typelib::RegistryExport::NotFound: cannot find a type named /base/samples/args in registry
	from /opt/workspace/rock-master/install/lib/ruby/2.0.0/typelib/registry_export.rb:145:in `method_missing'
	from /opt/workspace/rock-master/install/lib/ruby/2.0.0/typelib/registry_export.rb:153:in `const_missing'
	from (irb):3
	from /usr/bin/irb2.0:12:in `<main>'
irb(main):004:0>

**Comment by doudou** [comment]
You have a typo in the type name (and there's a bug in the error message generation)

**Comment by doudou** [comment]
Error message should be fixed by https://github.com/orocos-toolchain/typelib/pull/58

**Comment by 2maz** [comment]
K, checked again for existing and non-existing type and looks good now. Thanks.

**Comment by doudou** [comment]
Have you had a look at the base/types change ? (rock-core/base-types#53). It's backward-incompatible, so I would be glad if you could at least ack it there ...

**Comment by 2maz** [comment]
Ack on the technical part. However, I don't see how that fits with the current deprecation policy and warning users first. Adding that commit will require an immediate change :/

**Comment by doudou** [comment]
> However, I don't see how that fits with the current deprecation policy and warning users first.

(1) most users don't require the SISL spline bindings directly, they only use them through the typelib stuff (which would still work)
(2) there's no way to retain backward compatibility, I've spent an hour trying different things to make it work and failed. In addition, the typelib change was more than necessary (the typelib export was utter crap, and full of bugs).

I personally believe that this entails an exception to the break-backward-compatibility thing. Opinions ?

**Comment by goldhoorn** [comment]
On 19.06.2015 14:33, Sylvain Joyeux wrote:
>
>     However, I don't see how that fits with the current deprecation
>     policy and warning users first.
>
> (1) most users don't require the SISL spline bindings directly, they 
> only use them through the typelib stuff (which would still work)
> (2) there's no way to retain backward compatibility, I've spent an 
> hour trying different things to make it work and failed. In addition, 
> the typelib change was more than necessary (the typelib export was 
> utter crap, and full of bugs).
>
> I personally believe that this entails an exception to the 
> break-backward-compatibility thing. Opinions ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/issues/67#issuecomment-113500616>.
>
I think this is okay.

But since this would cause a ruby-runtime-error it is possible to create 
a class which raises a clear error if it got instanciated.
This would then point to the problem, instead of only getting a error 
"unknown type"


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
> But since this would cause a ruby-runtime-error it is possible to create
a class which raises a clear error if it got instanciated.
> This would then point to the problem, instead of only getting a error
"unknown type"

I don't understand that one. This would require to explicitely create a class in the Types:: hierarchy, which is the very thing that cannot be done.

**Comment by goldhoorn** [comment]
On 19.06.2015 14:57, Sylvain Joyeux wrote:
>
>     But since this would cause a ruby-runtime-error it is possible to
>     create
>     a class which raises a clear error if it got instanciated.
>     This would then point to the problem, instead of only getting a error
>     "unknown type"
>
> I don't understand that one. This would require to explicitely create 
> a class in the Types:: hierarchy, which is the very thing that cannot 
> be done.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/issues/67#issuecomment-113507732>.
>

ah okay

-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
https://github.com/rock-core/base-types/pull/53 is merged, closing.
