### ISSUE TITLE
Can't use transformer with ruby2.0

### ISSUE THREAD

**Issue by skasperski** [rock-core/tools-orocosrb#71]
I have a very simple task, which only provides a single transformation and want to test it with a simple script. But every call to "Orocos.transformer" leads to this error:

    .../install/lib/ruby/2.0.0/transformer/runtime.rb:47:in `reset': uninitialized constant Types::Transformer::ConfigurationState (NameError)
	from /home/dfki.uni-bremen.de/skasperski/Robotics/rock-slam3d/install/lib/ruby/2.0.0/transformer/runtime.rb:43:in `initialize'
	from /home/dfki.uni-bremen.de/skasperski/Robotics/rock-slam3d/install/lib/ruby/2.0.0/transformer/runtime.rb:282:in `new'
	from /home/dfki.uni-bremen.de/skasperski/Robotics/rock-slam3d/install/lib/ruby/2.0.0/transformer/runtime.rb:282:in `transformer'
	from start.rb:8:in `<main>'

The full start script is:

    require 'orocos'
    require 'transformer/runtime'
    
    include Orocos
    Orocos.initialize
    Orocos.transformer.load_conf('transforms.rb')
    
    Orocos.run 'transformer::TestTransformer' => 'test_task' do
        task = Orocos.name_service.get 'test_task'
        Orocos.transformer.setup(task)
        task.configure
        task.start
        while(true)
            sleep(1)
        end
    end

**Comment by 2maz** [comment]
Turns out the behaviour here is mainly due to an installation and naming conflict: 
drivers/orogen/transformer installs its typelib file *.tlb i.e. share/orogen/transformer.tlb
and the component used here for testing has been named: test/transformer/transformer.orogen thus installing also into share/orogen/transformer.tlb and overriding the existing file.

**Comment by doudou** [comment]
Given @2maz's analysis, this does not seem to be an orocos.rb bug, closing
