### ISSUE TITLE
Unable to use base types from ruby

### ISSUE THREAD

**Issue by planthaber** [rock-core/tools-orocosrb#72]
Hi, I am currently unable to use Types::Base:: types in ruby (undefined)

Also, I was unable to load a transformer config, perhaps related to:
https://github.com/rock-core/tools-orocosrb/issues/71

I first suspected
https://github.com/orocos-toolchain/orogen/pull/15

but revertign the merge does not help

**Comment by goldhoorn** [comment]
duplicate to?: https://github.com/rock-core/tools-orocosrb/issues/67

**Comment by planthaber** [comment]
I think so, but it looks like it also breaks the transformer configuration from scripts

**Comment by doudou** [comment]
This looks like the symptom fixed by https://github.com/rock-core/base-types/pull/53. Since I can't reproduce anymore, I'm closing this. Feel free to reopen if you hit the problem again.
