### ISSUE TITLE
Error in error message base.rb l 186

### ISSUE THREAD

**Issue by shoppel** [rock-core/tools-orocosrb#83]
if !deployment
    raise InternalError, "cannot find the deployment called #{name} in #{project.name}. 
            Candidates were #{project.deployers.map(&:name).sort.join(", ")}"
end

Sth wrong with the "Candidates were" ... part, just got 
`each': undefined method`name' for #Array:0x00000003c4a970

**Comment by goldhoorn** [comment]
Please add the full backtrace

On 28.08.2015 14:19, shoppel wrote:
>
> if !deployment
> raise InternalError, "cannot find the deployment called #{name} in 
> #{project.name}.
> Candidates were #{project.deployers.map(&:name).sort.join(", ")}"
> end
>
> Sth wrong with the "Candidates were" ... part, just got
> |each': undefined method|name' for #Array:0x00000003c4a970
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/issues/83>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by goldhoorn** [comment]
@shoppel : can you provide a BT otherwise i close this Issue
